### ISSUE TITLE
Facebook share: score mismatch

### ISSUE THREAD

**Issue by lucaro** [s3inlc/cineast-evaluator#9]
The score displayes in the facebook share preview does not match the displayed score:
![image](https://cloud.githubusercontent.com/assets/246519/26603445/26bbe474-4587-11e7-9d51-08ebb6923543.png)
This is probably because of the order in which achievements influence the updating of the multiplayer.

**Comment by s3inlc** [comment]
The change should fix this issue, as it should not count achievements which were received at the very same time when the score was calculated. So on later page calls (like Facebook does when you are sharing), it should stay the same.

If you can reproduce such a situation, please report back if the issue is fixed.

**Comment by lucaro** [comment]
Appears to be working correctly now.
